name: Deploy wordpress via LightSail

on:
  workflow_dispatch:
jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout the repostory with Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Initialise project and view terraform plan
        run: |
          terraform init 
          terraform plan
  deploy:
    name: Deploy infrastructure
    needs: plan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout the repository with Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Refresh state from S3 bucket and deploy the infrastructure
        run: |
          terraform init
          terraform apply --auto-approve
