name: Destroy wordpress based on LightSail

on:
  workflow_dispatch:
jobs:
  plan:
    name: Terraform destroy
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Check out repository with Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Refresh state from S3 bucket and destroy the infrastructure
        run: |
          terraform init 
          terraform destroy --auto-approve
